version: 2.1


workflows:
  version: 2
  build:
    jobs:
      - bitcoin-listener:
          filters:
            branches:
              only:
                - dev
                - master
      - bitcoin-rpc:
          filters:
            branches:
              only:
                - dev
                - master
      - binance-smart-chain-rpc:
          filters:
            branches:
              only:
                - dev
                - master
      - ethereum-listener:
          filters:
            branches:
              only:
                - dev
                - master
      - ethereum-rpc:
          filters:
            branches:
              only:
                - dev
                - master
      - gateway:
          filters:
            branches:
              only:
                - dev
                - master
      - developers:
          filters:
            branches:
              only:
                - dev
                - master

executors:

  ubuntu:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false


commands:

  docker_login:
    steps:
      - run: docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}


jobs:

  bitcoin-listener:
    executor: ubuntu
    steps:
      - checkout
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f bitcoin-listener/src/Dockerfile . -t 'theapis/apis-core-bitcoin-listener:latest'"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f bitcoin-listener/src/Dockerfile . -t 'theapis/apis-core-bitcoin-listener:stable'"
      - docker_login
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-bitcoin-listener:latest"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-bitcoin-listener:stable"

  bitcoin-rpc:
    executor: ubuntu
    steps:
      - checkout
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f bitcoin-rpc/src/Dockerfile . -t 'theapis/apis-core-bitcoin-rpc:latest'"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f bitcoin-rpc/src/Dockerfile . -t 'theapis/apis-core-bitcoin-rpc:stable'"
      - docker_login
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-bitcoin-rpc:latest"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-bitcoin-rpc:stable"

  binance-smart-chain-rpc:
    executor: ubuntu
    steps:
      - checkout
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f binance-smart-chain-rpc/src/Dockerfile . -t 'theapis/apis-core-binance-smart-chain:latest'"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f binance-smart-chain-rpc/src/Dockerfile . -t 'theapis/apis-core-binance-smart-chain:stable'"
      - docker_login
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-binance-smart-chain-rpc:latest"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-binance-smart-chain-rpc:stable"

  ethereum-listener:
    executor: ubuntu
    steps:
      - checkout
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f ethereum-listener/src/Dockerfile . -t 'theapis/apis-core-ethereum-listener:latest'"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f ethereum-listener/src/Dockerfile . -t 'theapis/apis-core-ethereum-listener:stable'"
      - docker_login
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-ethereum-listener:latest"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-ethereum-listener:stable"

  ethereum-rpc:
    executor: ubuntu
    steps:
      - checkout
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f ethereum-rpc/src/Dockerfile . -t 'theapis/apis-core-ethereum-rpc:latest'"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f ethereum-rpc/src/Dockerfile . -t 'theapis/apis-core-ethereum-rpc:stable'"
      - docker_login
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-ethereum-rpc:latest"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-ethereum-rpc:stable"

  gateway:
    executor: ubuntu
    steps:
      - checkout
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f gateway/src/Dockerfile . -t 'theapis/apis-core-gateway:latest'"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f gateway/src/Dockerfile . -t 'theapis/apis-core-gateway:stable'"
      - docker_login
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-gateway:latest"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-gateway:stable"

  developers:
    executor: ubuntu
    steps:
      - checkout
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f developers/Production.Dockerfile ./developers -t 'theapis/apis-core-developers:latest'"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker build -f developers/Production.Dockerfile ./developers -t 'theapis/apis-core-developers:stable'"
      - docker_login
      - when:
          condition:
            equal: [ "dev", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-developers:latest"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                command: "docker push theapis/apis-core-developers:stable"
