---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ethereum-rpc
  name: ethereum-rpc
  namespace: apis
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: ethereum-rpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ethereum-rpc
  name: ethereum-rpc
  namespace: apis
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      run: ethereum-rpc
  template:
    metadata:
      labels:
        run: ethereum-rpc
    spec:
      containers:

      - name: ethereum-rpc
        image: theapis/apis-core-ethereum-rpc:latest
        command: ["npm", "start"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "2048Mi"
            cpu: "400m"
        ports:
        - containerPort: 8103
        livenessProbe:
          exec:
            command:
            - echo
            - "alive"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - echo
            - "alive"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        envFrom:
          - configMapRef:
              name: apis
        env:
          - name: EXPRESS_PORT
            value: "8103"
          - name: POSTGRES_DATABASE
            value: "EthereumRinkeby"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ethereum-listener
  name: ethereum-listener
  namespace: apis
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      run: ethereum-listener
  template:
    metadata:
      labels:
        run: ethereum-listener
    spec:
      containers:

      - name: ethereum-listener
        image: theapis/apis-core-ethereum-listener:latest
        command: ["npm", "start"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "3096Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8104
        livenessProbe:
          exec:
            command:
            - echo
            - "alive"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - echo
            - "alive"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        envFrom:
          - configMapRef:
              name: apis
        env:
          # - name: NODE_ENV
          #   value: ""

          # - name: POSTGRES_HOST
          #   value: ""
          # - name: POSTGRES_PORT
          #   value: ""
          # - name: POSTGRES_USER
          #   value: ""
          # - name: POSTGRES_PASSWORD
          #   value: ""
          - name: POSTGRES_DATABASE
            value: "EthereumRinkeby"

          # - name: REDIS_URL
          #   value: ""
          # - name: REDIS_HOST
          #   value: ""
          # - name: REDIS_PORT
          #   value: ""
          - name: REDIS_PREFIX
            value: "ethereum-rinkeby"

          # - name: ETHEREUM_WSS_USER
          #   value: ""
          # - name: ETHEREUM_WSS_PASS
          #   value: ""
          - name: ETHEREUM_WSS_ADDR
            value: ""

          - name: ETHEREUM_MIN_BLOCK_NUMBER
            value: "0"
